# Site settings
title: yasha mostofi
email: yasha.mostofi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  todo: write cool things
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://yashamostofi.com/" # the base hostname & protocol for your site
twitter_username: ymostofi
github_username: redsn0w422

# Build settings
markdown: kramdown
